"""Update schema for comprehensive restaurant system

Revision ID: 928778736f34
Revises: 
Create Date: 2025-04-24 03:59:31.235176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928778736f34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_times')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eater_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('table_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reservation_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('reservation_time', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('party_size', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tables', ['table_id'], ['id'])
        batch_op.create_foreign_key(None, 'eaters', ['eater_id'], ['id'])
        batch_op.drop_column('time')
        batch_op.drop_column('guests')
        batch_op.drop_column('email')
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('has_parking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accepts_reservations', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('location')
        batch_op.drop_column('rating')
        batch_op.drop_column('cuisine')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('accepts_reservations')
        batch_op.drop_column('has_parking')
        batch_op.drop_column('website_url')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('average_rating')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('guests', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('party_size')
        batch_op.drop_column('reservation_time')
        batch_op.drop_column('reservation_date')
        batch_op.drop_column('table_id')
        batch_op.drop_column('eater_id')

    op.create_table('available_times',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
